# Generated by Django 6.0 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_author_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='main_app.genre'),
        ),
    ]
